import type { Metadata } from "next";
import "./globals.css";
import Container from "@/app/components/Container";
import Navbar from "@/app/components/Navbar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`min-h-full 2xl:px-0 flex flex-col font-(family-name:--font-montserrat) bg-gray-50 h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <main className="flex-auto mb-5">
                    <div className="mx-auto w-full h-full">
                        {children}
                    </div>
                </main>
            </body>
        </html>
    );
}
